### ISSUE TITLE
Build now hook does not find Git projects using Multiple SCMs plugin

### ISSUE THREAD

**Issue by adamdougal** [elvanja/jenkins-gitlab-hook-plugin#21]
I'm trying to use the /gitlab/build_now hook with my projects, however I think that because I'm using the Multiple SCMs plugin (https://wiki.jenkins-ci.org/display/JENKINS/Multiple+SCMs+Plugin) my projects aren't being found and I'm getting the Jenkins warning log message:

no project references the given repo url and commit branch

**Comment by kalibyrn** [comment]
...just wanted to throw my moral support behind this idea.  :+1: 

@elvanja, if you happen to find the time, you can be sure that I would be much appreciated of this change!  Also, thanks for taking the time to write the plug-in to begin with.

**Comment by alesandreo** [comment]
As a workaround, could you do a dummy job that checks something out from your git repo and then as a post build task builds your Multi SCM plugin?
