### ISSUE TITLE
Gitlab web hook fails when Cross Site Request Forgery protection is active

### ISSUE THREAD

**Issue by jcsirot** [elvanja/jenkins-gitlab-hook-plugin#30]
When the CSRF protection is set in Jenkins security config, the web hook requests fail with this error:

```
Jun 9, 2014 9:31:58 AM hudson.security.csrf.CrumbFilter doFilter
WARNING: No valid crumb was included in request for /gitlab/notify_commit. Returning 403.
```

This is caused by the POST request which does not use a crumb.

A simple fix could be implementing a `CrumbExclusion` in the plugin like the gitbucket plugin 
(see https://github.com/jenkinsci/gitbucket-plugin/blob/master/src%2Fmain%2Fjava%2Forg%2Fjenkinsci%2Fplugins%2Fgitbucket%2FGitBucketWebHook.java)

(I already opened a ticket in Jenkins JIRA JENKINS-23370; but maybe here is a better place)

**Comment by Kraeutergarten** [comment]
Same Problem now again.

**Comment by daikaixian** [comment]
Same Problem now again.

**Comment by MaikoHermans** [comment]
@daikaixian I second this

**Comment by matt-dalton** [comment]
Also found this

**Comment by pablonvz** [comment]
Same problem here
