### ISSUE TITLE
Skip a build job

### ISSUE THREAD

**Issue by stefanjauker** [elvanja/jenkins-gitlab-hook-plugin#55]
Hello guys,

I have 2 build jobs for the same repository.
The first build job is triggered by a gitlab webhook. It works as expected.
The 2nd is a nightly build and should not started by the webhook.

Is there a possibility to skip/ignore a job?

Thanks for your help

Stefan

**Comment by elvanja** [comment]
Hi @stefanjauker, sure, you just need to open job configuration and set "skip notifyCommit" option in Git section. The job will always be skipped.

**Comment by seepick** [comment]
to be precisly, its an additional behaviour called `Don't trigger a build on commit notifications`. it works, although this setting is provided by Jenkins GIT Plugin, rather from this GitLab Hook Plugin.
