### ISSUE TITLE
only string parameters for branch parameter are supported

### ISSUE THREAD

**Issue by pandian912** [elvanja/jenkins-gitlab-hook-plugin#56]
I am trying to get the tag value as a git paramater, the default value is the branch to build (*/master)

but getting the error in jenkins log
only string parameters for branch parameter are supported

**Comment by elvanja** [comment]
Hi, current version of plugin supports only String parameters for branch in job configuration. Essentially, we don't know how to fill in other types of parameters. So, when you setup parameters to fill, you should add the branch name parameter, and tag as well, and both should be strings. Let me know if that doesn't help.

**Comment by pandian912** [comment]
Can we just set the plugin to ignore any other type of parameter, instead of throwing an exception. I would like to take the default value for the parameter and continue working...

I have setup a job(A) and set it to "Don't trigger a build on commit notifications" and this job uses a git parameter....
I have an other job(B) which should be triggered on any change in the repo.

But because of the first job which uses a non-string parameter, the second job is also not triggered...

**Comment by elvanja** [comment]
Yes, you can have that. Actually it is already there. I just forgot to release it. There is a new version 1.2.0 that does just that, ignores all but String type parameters. If you can't see it in updates yet, download and install manually from http://maven.jenkins-ci.org/content/repositories/releases/org/jenkins-ci/ruby-plugins/gitlab-hook/1.2.0.
