### ISSUE TITLE
Auto project creation

### ISSUE THREAD

**Issue by fkrauthan** [elvanja/jenkins-gitlab-hook-plugin#57]
I recently tried to turn on the automatic project copy mode. But I always get the error message that it can't find the master project. But if I push to master it finds the project for the master branch and starts building it. Is there more documentation how I have to setup the git repository in my master jenkins job so the plugin can find it?

**Comment by elvanja** [comment]
Hi! I wasn't really ever using this feature. But feel free to post the issue @ https://github.com/javiplx/jenkins-gitlab-hook-plugin. Maybe he can help.
