### ISSUE TITLE
naming autogenerated project does not postfix with branchname on first creation

### ISSUE THREAD

**Issue by LogikBlitz** [elvanja/jenkins-gitlab-hook-plugin#60]
According to documentation an autogenerated project should be named by the repo name and then postfixed with the branch, i.e. `REPONAME_BRANCH`

In my testing i have observed that this is not the case the first time a project is created from an unknown repository notification. Then the name of the Jenkins project will match only the gitlab repo name and not prefix the branchname.

Setup:
- Jenkins 1.615
- Gitlab hook plugin: 1.4.0
- Automatic project creation is ON
- Template based job creation is used and ONLY `base project` has a value

![gitlabhookpluginsetup](https://cloud.githubusercontent.com/assets/560415/7877688/8de66376-05de-11e5-894f-3e05bc205222.png)

Scenario:
Prerequisite.
- Reponame `FOO`
- Gitlab repo `FOO` has webhook to jenkins using `build_now`
- Jenkins does not have a Project relating to repo `FOO`

Reproduce:
1. Commit to `master` branch of repo `FOO`
2. Jenkins/plugin recieves notification and creates project named `FOO`. _Expected name should be_ `FOO_master`
3. Commit to `master` branch of repo `FOO` again and observe that Jenkins/plugin creates a _new_ project named `FOO_master`. This is wierd since the Jenkins project `FOO` relate to the `master` branch
4. Commit to `develop` branch of repo `FOO`
5. Jenkins/Plugin recieves notification and creates project named `FOO_develop` as expected. According to log the project `FOO_develop` is based on project `FOO`

**Comment by LogikBlitz** [comment]
Bump

**Comment by javiplx** [comment]
Already filed as [JENKINS-28973](https://issues.jenkins-ci.org/browse/JENKINS-28973), please close this issue.
