### ISSUE TITLE
How could I skip building based on commit message?  (Enhancement Request?)

### ISSUE THREAD

**Issue by mikedon** [elvanja/jenkins-gitlab-hook-plugin#62]
right now we have our repositories set up in gitlab to trigger whenever a push happens to master using the web hooks.  The webhook is set up to invoke jenkins by way of this great plugin. 

We also use a jenkins build to automatically increase the pre release version of our software and push to master.  This means we have an infinite build loop.

What I would like to do is skip a build based on some value in a commit message.  I imagine this would be a good enhancement to this plugin but I'm not sure if thats the appropriate place for it or if someone is aware of another way to achieve this.

**Comment by javiplx** [comment]
Please, open an issue on [Jenkins jira](https://issues.jenkins-ci.org/), with component gitlab-hook-plugin and close this issue (I have no permission).
In any case, I do not understand your use case well. What I understand is that every push to master will increase the release number, and if that is the case you'll end in an infinite loop. At some point in the mid-term future, it will be possible to avoid builds for commits of certain users, which should cover your use case, but it is not a matter of days.
