### ISSUE TITLE
Does not install on Jenkins 1.635

### ISSUE THREAD

**Issue by roll4life** [elvanja/jenkins-gitlab-hook-plugin#63]
It appears that upgrading to versions of Jenkins 1.633 and greater will cause this plugin to no longer work due to an issue with the ruby runtime plugin.
https://issues.jenkins-ci.org/browse/JENKINS-31019?jql=project%20%3D%20JENKINS%20AND%20status%20in%20%28Open%2C%20%22In%20Progress%22%2C%20Reopened%29%20AND%20component%20%3D%20%27ruby-runtime-plugin%27

Until the ruby runtime plugin is fixed, it may be helpful to update the documentation to let people know that this will only work on Jenkins 1.632 and earlier.

**Comment by Cactusbone** [comment]
from https://issues.jenkins-ci.org/browse/JENKINS-31019?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27ruby-runtime-plugin%27

you can use `-Dhudson.ClassicPluginStrategy.noBytecodeTransformer=true`

**Comment by javiplx** [comment]
This is already solved. Currently, acceptance tests are run on the latest three LTS Jenkins version, and on the latest Jenkins core version (although this is obviously a moving one). So, please close this issue (I have no permission).
